pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      # - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-bintray
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: Bintray
  desc: Publish files and artifacts to Bintray
  type: publish
  image: plugins/drone-bintray
  labels:
    - publish
    - bintray
    - artifacts
