build:
  image: golang:1.5
  environment:
    - CGO_ENABLED=0
  commands:
    - make deps
    - make vet
    - make build
    - make test

publish:
  coverage:
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-bintray
    tag: latest
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-bintray
    tag: develop
    when:
      branch: develop

plugin:
  name: Bintray
  desc: Publish files and artifacts to Bintray
  type: publish
  image: plugins/drone-bintray
  labels:
    - publish
    - bintray
    - artifacts
